### ISSUE TITLE
Onglet de crafting REI manquant pour Chipped

### ISSUE THREAD

**Issue by Salvard** [iglee42/CreateQualityOfLife#11]
Hello !

La mise à jour de Chipped 1.20.1-3.0.7 pour forge semble avoir fait sauter les onglets de crafting de ce mod, ce qui m'embête car ils sont bien plus clair que ce de base de Chipped...
Pour le coup je suis sous REI, mais c'est possible que ça est sauter aussi sous JEI

Bonne continuation !

**Comment by iglee42** [comment]
Yop je pense que tu t'es trompé de mod car ce mod n'ajoute pas d'onglet dans JEI

**Comment by Salvard** [comment]
Ah ! Et bah RIP, vu que les l'onglets de craft incluais aussi les scies chipped/create de ce mod, j'était persuadé que c'était lui qui les avais rajouté ^^'


Bonne continuation et désolé pour le dérangent 👍

**Comment by iglee42** [comment]
Pas grave tkt ça arrive de se tromper
