### ISSUE TITLE
[Crash] When using the chipped work bench the game crashes

### ISSUE THREAD

**Issue by mcclellanja** [iglee42/CreateQualityOfLife#3]
Tried the Botany and Mason saws and crashed both times. Here are the crash reports (i''l put them in separate comments if that helps). Note I never used the alchemy bench type but have it placed in my world but that is pointed to in each crash for both the botany and mason work benches.

**Comment by mcclellanja** [comment]
[crash-2024-02-14_15.02.53-server.txt](https://github.com/iglee42/CreateQualityOfLife/files/14289554/crash-2024-02-14_15.02.53-server.txt)
[crash-2024-02-14_15.17.52-server.txt](https://github.com/iglee42/CreateQualityOfLife/files/14289555/crash-2024-02-14_15.17.52-server.txt)

Sorry didn't realize you could just attach files

**Comment by iglee42** [comment]
Which version of Chipped are you using ?

**Comment by mcclellanja** [comment]
The Chipped forge 1.20.1 - 3.0.4 
And the latest CreateQOL version 1.0 

EDIT:
Just tested, everyting works on 3.0.1 but from version 3.0.2 and above it crashes

**Comment by iglee42** [comment]
OK, for the moment I don't have access to my computer so I can't fix it, and thanks for your video

**Comment by quinman24** [comment]
if possible can you update the create: quality of life mod so this mod can work with the latest version of chipped forge 3.0.4 for Minecraft 1.20.1?

**Comment by iglee42** [comment]
> if possible can you update the create: quality of life mod so this mod can work with the latest version of chipped forge 3.0.4 for Minecraft 1.20.1?

For the moment I don't have access to my computer so it's hard to update the mod.

**Comment by iglee42** [comment]
Fixed thanks :)
