### ISSUE TITLE
Missing textures because off chipped update 

### ISSUE THREAD

**Issue by VillainVibe** [iglee42/CreateQualityOfLife#9]
The textures show are unkown checkers blocks because chipped changed the look off the chipped workbenches 
Im using the lastest version 3.0.6 for 1.20.1

Example off how the QoL chipped cutters look in JEI
![2024-04-18_15 07 48](https://github.com/iglee42/CreateQualityOfLife/assets/161154905/288c446c-7afb-4246-8551-44aaa9b45da2)

**Comment by ali-afk** [comment]
Same, am I using it in a server so it's quite annoying.

**Comment by iglee42** [comment]
I will hotfix this during the week-end

**Comment by iglee42** [comment]
Fixed
